/* eslint-disable react/no-unescaped-entities */
/* eslint-disable @next/next/no-page-custom-font */
import type { NextPage } from 'next';
import { useState } from 'react';
import Head from 'next/head';
import Script from 'next/script';
import Image from 'next/image';
import styles from '../styles/Home.module.css';


const Home: NextPage = () => {
  return (
    <>
    
      <div id="main">
        <Head>
          <title>My lesson</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet"/>
          <link rel="iconarrow" href="/downarrow.png" />
        </Head>
        <div className="container">

           {/*  Section page 1 */}
          <section id="section-1">
            <div className="main-section">
              <div id="column1"></div>
              <h1 id="title-tribute">TRIBUTE</h1>
              <div id="nav-bar">
                <a id="about" href="" target="_blank">ABOUT</a>
                <a id="info" href="" target="_blank">INFO</a>
              </div>
              <div className="img" id="div-img"></div>
              <div id="title-div">
                <h4  id="title-name">Dr. Norman Borlaug</h4>
                <p id="title-info">The man who <br/> saved a billion lives</p> 
                <time id="years">1914 - 2009</time>
              </div>
              <div id="img-caption">Dr. Norman Borlaug, third from the left, trains biologists in Mexico on how to increase wheat yields - part of his life-long war on hunger.
              </div>
              <div id="box-arrow-s-1">
                <a href="#section-2" type="image" id="arrow-input"></a>
              </div>
              <div id="column2"></div>
            </div>
          </section>
          {/*  End page 1*/}

          {/*  Section page 2 */}   
          <section id="section-2">
            <div className="main-section-2">
                <div id="s-2-text-1">
                  <div id="box-blue-1">
                    <h3 id="title-1">March 25, 1914 Born in Cresco, Iowa</h3>
                  </div>
                  <p id="p-1">Norman Borlaug was born to Henry Oliver (1889–1971) and Clara (Vaala) Borlaug (1888–1972) on his grandparents' farm in Saude in 1914, the first of four children. His three sisters were Palma Lillian (Behrens; 1916–2004), Charlotte (Culbert; b. 1919) and Helen (b. 1921).</p>
                </div>
                <time id="year-1914">1914</time>
                <div id="s-2-text-2">
                  <div id="box-blue-2"><h3 id="title-2">1933 - Norman Bourlaug Admission to the Minnesota University</h3></div>
                  <p id="p-2">1933 - Norman Bourlaug leaves his family's farm to attend the University of Minnesota, thanks to a Depression era program known as the National Youth "Administration"</p>
                </div>
                <time id="year-1933">1933</time>
                
                <div id="fotofamily">
                  <Image src="/family.png" alt="Familie"  width="420" height="270" id="imagfamily"/>
                </div>
                
                <div id="fotouniver">
                  <Image src="/univer.png" alt="univer" width={544} height={227}/>
                </div>
                <div id="box-arrow-s-2">
                  <a href="#section-3" type="image" id="down-arrow-page-2"></a>
                  <a href="#section-1" type="image" id="top-arrow-page-2"></a>
                </div>
            </div>
          </section> 
          {/*  End page 2 */}

          {/*  Section page 3 */}
          <section id="section-3">
            <div className="main-s-3">
                <div id="s-3-text-1">
                  <div id="s-3-box-blue-1">
                    <h3 id="s-3-title-1"> 1935 Civilian Conservation Corps</h3>
                  </div>
                  <p id="s-3-p-1">
                    Stop school Norman Bourlaug has to stop school and save up more money. Works in the Civilian Conservation Corps, helping starving Americans."I saw how food changed them", he said. "All of this left scars on me."
                  </p>
                </div>
                <time id="year-1935">1935</time>
                <div id="sect-3-text-2">
                  <div id="s-3-box-blue-2">
                    <h3 id="s-3-title-2">1937  US Forestry Service
                    </h3>
                  </div>
                  <p id="s-3-p-2">Norman Bourlaug finishes university and takes a job in the US Forestry Service
                  </p>
                </div>
                <time id="year-1937">1937</time>
                
                <div id="fotoforest">
                  <Image src="/natonalforest.png" alt="forest"  width="420" height="250" id="imgforest"/>
                </div>
                
                <div id="fotoworkforest">
                  <Image src="/workforest.png" alt="workforestimage" width={544} height={227}/>
                </div>
                <div id="box-arrow-s-3">
                  <a href="#section-4" type="image" id="down-arrow-page-3"></a>
                  <a href="#section-2" type="image" id="top-arrow-page-3"></a>
                </div>
            </div>
          </section> 
          {/*  End page 3 */}

          {/*  Section page 64*/}
          <section id="section-4">
            <div className="main-s-4">
                <div id="s-4-text-1">
                  <div id="s-4-box-blue-1">
                    <h3 id="s-4-title-1">Norman Bourlaug marries</h3>
                  </div>
                  <p id="s-4-p-1">
                  1938    Norman Bourlaug marries his 24-year-old wife, Margret Gibson. It is made available due to budget cuts. Inspired by Elvin Charles Stakman, he returns to school under Stakman, who teaches him how to grow pest-resistant plants.
                  </p>
                </div>
                <time id="year-1938">1938</time>
                <div id="sect-4-text-2">
                  <div id="s-4-box-blue-2">
                    <h3 id="s-4-title-2">Norman Bourlaug in  Mexico <br/> head a new plant pathology program
                    </h3>
                  </div>
                  <p id="s-4-p-2">1944 Norman Bourlaug rejects a 100% salary increase from Dupont, leaves behind his pregnant wife, and flies to Mexico to head a new plant pathology program. 
                  Over the next 16 years, his team breeds 6,000 different strains of disease resistent wheat - including different varieties for each major climate on Earth.
                  </p>
                </div>
                <time id="year-1944">1944</time>
                
                <div id="fotowithwife">
                  <Image src="/withwife.png" alt="withwife"  width="420" height="250" id="imgforest"/>
                </div>
                
                <div id="fotomorewomen">
                  <Image src="/fotomorewomen.png" alt="fotomorewomen" width={544} height={227}/>
                </div>
                <div id="box-arrow-s-4">
                  <a href="#section-5" type="image" id="down-arrow-page-4"></a>
                  <a href="#section-3" type="image" id="top-arrow-page-4"></a>
                </div>
            </div>
          </section> 
          {/*  End page 4 */}

           {/*  Section page 5 */}
          <section id="section-5">
            <div className="main-s-5">
                <div id="s-5-text-1">
                  <div id="s-5-box-blue-1">
                    <h3 id="s-5-title-1">Norman Bourlaug visits Delhi
                    </h3>
                  </div>
                  <p id="s-5-p-1">1962 Norman Bourlaug Visits Delhi and brings his high-yielding strains of wheat to the Indian subcontinent in time to help mitigate mass starvation due to a rapidly expanding population
                  </p>
                </div>
                <time id="year-1962">1962</time>
                <div id="s-5-text-2">
                  <div id="s-5-box-blue-2">
                    <h3 id="s-5-title-2">Norman Borlaug's 2005 speech
                    </h3>
                  </div>
                  <p id="s-5-p-2">In his 2005 speech, Norman Bourlaug stated that "we will have to double the world's food supply by 2050."
                       He argues that genetically modified crops are the only way we can meet demand because we run out of arable land. He says genetically modified crops are not inherently dangerous because "we've been genetically modifying plants and animals for a long time. Long before we called it science, humans chose the best breeds."
                  </p>
                </div>
                <time id="year-2005">2005</time>
                
                <div id="fotowithpeople">
                  <Image src="/N.B.withthepeoples.png" alt="withpeople"  width="420" height="250" id="imgwithwififoto"/>
                </div>
                
                <div id="fotospeaks">
                  <Image src="/FOTOWHENNBSPEAKS.png" alt="speaks" width={544} height={227}/>
                </div>

                <div id="box-arrow-s-5"> 
                  <a href="#section-6" type="image" id="down-arrow-page-5"></a>
                  <a href="#section-4" type="image" id="top-arrow-page-5"></a>
                </div>

            </div>
          </section> 
          {/*  End page 5 */}
            
          {/*  Section page 6 */}
          <section id="section-6">
            <div className="main-s-6">
                <div id="s-6-text-1">
                  <div id="s-6-box-blue-1">
                    <h3 id="s-6-title-1"> Norman Bourlaug dies</h3>
                  </div>
                  <p id="s-6-p-1">2009 Norman Bourlaug dies at the age of 95.</p>
                </div>
                <time id="year-2009">2009</time>
                <div id="fotonorman">
                  <Image src="/fotogreenplants.png" alt="fotonormanbourlaug" width={544} height={227}/>
                </div>
                <div id="s-6-text-2">
                  <div id="div-s-6-box-blue-2">
                    <div id="s-6-box-blue-2">
                      <h3 id="s-6-title-2">More info on the wikipedia</h3>
                    </div>
                  </div>
                  
                </div>
                <div id="box-arrow-s-6"> 
                  <a href="#section-5" type="image" id="top-arrow-page-6">
                  </a>
                </div>
               
            </div>
          
            <footer>
              <div id="box-footer">
                <p id="footer-element"> ©2019 omiron.software All Rights Reserved</p>
               
              </div>
            </footer>
          
          </section> 
          {/*  End page 6 */}

        </div>
      </div>
      <Script src="https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js"></Script>
    </>  
  );
};
           
export default Home;
