/* eslint-disable react/no-unescaped-entities */
/* eslint-disable @next/next/no-page-custom-font */
import type { NextPage } from 'next';
import { useState } from 'react';
import Head from 'next/head';
import Script from 'next/script';
import Image from 'next/image';
import styles from '../styles/Home.module.css';



const Home: NextPage = () => {
  return (
    <>
    
      <div id="main">
        <Head>
          <title>My lesson</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet"/>
          <link rel="iconarrow" href="/downarrow.png" />
        </Head>
        <section id="section-1">
          <div className="main-section-2">
            
              <div id="text-1">
                <div id="box-blue-1">
                  <h3 id="title-1">March 25, 1914 Born in Cresco, Iowa</h3>
                </div>
                <p id="p-1">Norman Borlaug was born to Henry Oliver (1889–1971) and Clara (Vaala) Borlaug (1888–1972) on his grandparents' farm in Saude in 1914, the first of four children. His three sisters were Palma Lillian (Behrens; 1916–2004), Charlotte (Culbert; b. 1919) and Helen (b. 1921).</p>
              </div>
              
              <time id="year-1914">1914</time>

              
              
              
              
              <div id="text-2">
                <div id="box-blue-2"><h3 id="title-2">1933 - Norman Bourlaug Admission to the Minnesota University</h3></div>
                
                <p id="p-2">1933 - Norman Bourlaug leaves his family's farm to attend the University of Minnesota, thanks to a Depression era program known as the National Youth "Administration"</p>
              </div>
              
              <time id="year-1933">1933</time>
              
              <div id="fotofamily"><Image
                  src="/family.png"
                  alt="Familie"
                  width={420}
                  height={260
                  }
                  
                /></div>

              <div className="img" id="img-page2-1933"></div>
            </div>
          
        </section>
      </div>
      <Script src="https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js"></Script>
    </>  
  );
};

export default Home;
        
        
          
            
            
             
            
              

            
            
            
           
            
            
            
            



          
            

          
          
          
        

 
  
         
      

        

          
        
      

